<a href="https://colab.research.google.com/github/RodrigoMR13/Faculdade-XP-Bootcamp1/blob/main/Aula_Kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

Verificando versões

In [ ]:
import sklearn
import plotly
print(f''' Verificando as versões das bibliotecas:\n
pandas: {pd.__version__}
numpy: {np.__version__}
sklearn: {sklearn.__version__}
plotly: {plotly.__version__}
''')

 Verificando as versões das bibliotecas:

pandas: 1.3.5
numpy: 1.21.6
sklearn: 1.0.2
plotly: 5.5.0



Coletando dados

In [ ]:
iris = pd.read_csv("https://raw.githubusercontent.com/ProfLeandroLessa/classroom-datasets/master/ANC/video_aulas/iris.csv", sep=';')

Analisando os dados coletados

In [ ]:
# Visualizando os dados
iris.head()
#iris.tail()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# Gerando algumas estatísticas com base nos dados
iris.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# Número de classes existentes no dataframe
iris['Class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
# Contando número de classes
len(iris['Class'].unique())

3

In [ ]:
# Avaliando o número de linhas e colunas do dataset
iris.shape

(150, 5)

In [ ]:
# Verificando se existe algum valor nulo
iris.isna().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
Class           0
dtype: int64

In [ ]:
# Verificando informações da base de dados
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Criando clusters com os dados das pétalas

In [ ]:
x_petala = iris.iloc[:,[2,3]].values
x_petala[:10]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

Normalizando os dados

In [ ]:
normalizar_dados = StandardScaler()
x_petala = normalizar_dados.fit_transform(x_petala)
x_petala[:10]

array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

Calculando o número de cluster

In [ ]:
wcss_petala = []
for i in range(1,11):
  kmeans_petala = KMeans(n_clusters=i, random_state=0)
  kmeans_petala.fit(x_petala)
  wcss_petala.append(kmeans_petala.inertia_)
print(wcss_petala)

[300.0000000000001, 54.14584701344988, 18.046983891906276, 12.307440251261843, 9.181131495513899, 7.215096212730807, 6.026593155951448, 5.173315218915379, 4.423975871969686, 3.9139417830543204]


In [ ]:
for i in range(len(wcss_petala)):
  print('cluster:', i, '- Valor do WCSS:', wcss_petala[i])

cluster: 0 - Valor do WCSS: 300.0000000000001
cluster: 1 - Valor do WCSS: 54.14584701344988
cluster: 2 - Valor do WCSS: 18.046983891906276
cluster: 3 - Valor do WCSS: 12.307440251261843
cluster: 4 - Valor do WCSS: 9.181131495513899
cluster: 5 - Valor do WCSS: 7.215096212730807
cluster: 6 - Valor do WCSS: 6.026593155951448
cluster: 7 - Valor do WCSS: 5.173315218915379
cluster: 8 - Valor do WCSS: 4.423975871969686
cluster: 9 - Valor do WCSS: 3.9139417830543204


Definindo melhor o número de clusters

In [ ]:
grafico_cotovelo_petala = px.line(x=range(1,11), y=wcss_petala)
grafico_cotovelo_petala.update_xaxes(title_text='Número de clusters')
grafico_cotovelo_petala.update_yaxes(title_text='Valor de WCSS')
grafico_cotovelo_petala.update_layout(title_text='Definindo o número de clusters', title_x=0.5)
grafico_cotovelo_petala.show()

Executar o algoritmo K-Means para as pétalas

In [ ]:
kmeans_petala = KMeans(n_clusters=3, random_state=0)
label_cluster_petala = kmeans_petala.fit_predict(x_petala)

In [ ]:
label_cluster_petala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

Visualizandoc centroides de cada cluster

In [ ]:
centroides_petala = kmeans_petala.cluster_centers_
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

Visualizando os dados agrupados com dados das pétalas

In [ ]:
grafico_petala = px.scatter(x=x_petala[:,0], y=x_petala[:,1], color = label_cluster_petala)
grafico_centroide_petala = px.scatter(x=centroides_petala[:,0], y=centroides_petala[:,1], size=[7,7,7])
grafico_final = go.Figure(data=grafico_petala.data + grafico_centroide_petala.data)
grafico_final.update_xaxes(title_text='Comprimento')
grafico_final.update_yaxes(title_text='Largura')
grafico_final.update_layout(title_text='Clusters', title_x=0.5)
grafico_final.show()

In [ ]:
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

Criando clusters com dados das sépalas

In [ ]:
x_sepala = iris.iloc[:,[0,1]].values
x_sepala = normalizar_dados.fit_transform(x_sepala)
x_sepala[:5]

array([[-0.90068117,  1.03205722],
       [-1.14301691, -0.1249576 ],
       [-1.38535265,  0.33784833],
       [-1.50652052,  0.10644536],
       [-1.02184904,  1.26346019]])

In [ ]:
wcss_sepalas = []
for i in range(1,11):
  kmeans_sepala = KMeans(n_clusters=i, random_state=0)
  kmeans_sepala.fit(x_sepala)
  wcss_sepalas.append(kmeans_sepala.inertia_)

In [ ]:
for i in range(len(wcss_sepalas)):
  print('cluster:', i, '- Valor do WCSS:', wcss_sepalas[i])

cluster: 0 - Valor do WCSS: 300.0
cluster: 1 - Valor do WCSS: 168.39262198361087
cluster: 2 - Valor do WCSS: 103.78982520596082
cluster: 3 - Valor do WCSS: 79.78319156422033
cluster: 4 - Valor do WCSS: 61.70659834761937
cluster: 5 - Valor do WCSS: 52.13668525175612
cluster: 6 - Valor do WCSS: 44.82457356697236
cluster: 7 - Valor do WCSS: 36.22858628889425
cluster: 8 - Valor do WCSS: 30.56569905329544
cluster: 9 - Valor do WCSS: 26.796317715913396


In [ ]:
grafico_cotovelo_sepala = px.line(x=range(1,11), y=wcss_sepalas)
grafico_cotovelo_sepala.update_xaxes(title_text='Número de clusters')
grafico_cotovelo_sepala.update_yaxes(title_text='Valor de WCSS')
grafico_cotovelo_sepala.update_layout(title_text='Definindo o número de clusters', title_x=0.5)
grafico_cotovelo_sepala.show()

In [ ]:
kmeans_sepalas = KMeans(n_clusters=3, random_state=0)
label_cluster_sepalas = kmeans_sepalas.fit_predict(x_sepala)

In [ ]:
label_cluster_sepalas

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2,
       2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2,
       0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [ ]:
centroides_sepalas =  kmeans_sepalas.cluster_centers_
centroides_sepalas

array([[-0.04825457, -0.89224112],
       [-0.97822861,  0.89321545],
       [ 1.20144049,  0.14411561]])

In [ ]:
grafico_sepala = px.scatter(x=x_sepala[:,0], y=x_sepala[:,1], color = label_cluster_sepalas)
grafico_centroide_sepala = px.scatter(x=centroides_sepalas[:,0], y=centroides_sepalas[:,1], size=[7,7,7])
grafico_final = go.Figure(data=grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final.update_xaxes(title_text='Comprimento')
grafico_final.update_yaxes(title_text='Largura')
grafico_final.update_layout(title_text='Clusters', title_x=0.5)
grafico_final.show()

Definindo função para gerar gráfico

In [ ]:
def gera_grafico(x, y, color, x_centroide, y_centroide):
  grafico = px.scatter(x=x,
                       y=y,
                       color=color)
  grafico_centroide = px.scatter(x=x_centroide,
                                 y=y_centroide)
  grafico_final = go.Figure(data=grafico.data + grafico_centroide.data)
  grafico_final.update_xaxes(title_text='Comprimento')
  grafico_final.update_yaxes(title_text='Largura')
  grafico_final.update_layout(title_text='Clusters', title_x=0.5)
  grafico_final.show()

Função para as pétalas

In [ ]:
x = x_petala[:,0]
y = x_petala[:,1]
color = label_cluster_petala
x_centroide = centroides_petala[:,0]
y_centroide = centroides_petala[:,1]

gera_grafico(x, y, color, x_centroide, y_centroide)

Função para as sépalas

In [ ]:
x = x_sepala[:,0]
y = x_sepala[:,1]
color = label_cluster_sepalas
x_centroide = centroides_sepalas[:,0]
y_centroide = centroides_sepalas[:,1]

gera_grafico(x, y, color, x_centroide, y_centroide)